package active

// MitreTechnique represents a single ATT&CK technique.
type MitreTechnique struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Tactic      string `json:"tactic"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

// AllTactics returns the ordered list of MITRE ATT&CK tactics.
var AllTactics = []string{
	"Reconnaissance",
	"Resource Development",
	"Initial Access",
	"Execution",
	"Persistence",
	"Privilege Escalation",
	"Defense Evasion",
	"Credential Access",
	"Discovery",
	"Lateral Movement",
	"Collection",
	"Command and Control",
	"Exfiltration",
	"Impact",
}

// FullMitreMatrix contains all MITRE ATT&CK Enterprise techniques organized by tactic.
// This is the comprehensive reference database used for matrix display.
var FullMitreMatrix = []MitreTechnique{
	// ── Reconnaissance ──
	{ID: "T1595", Name: "Active Scanning", Tactic: "Reconnaissance", Description: "Adversaries may scan victim infrastructure to gather information"},
	{ID: "T1595.001", Name: "Scanning IP Blocks", Tactic: "Reconnaissance", Description: "Scan IP blocks to identify live hosts"},
	{ID: "T1595.002", Name: "Vulnerability Scanning", Tactic: "Reconnaissance", Description: "Scan for vulnerabilities in victim systems"},
	{ID: "T1595.003", Name: "Wordlist Scanning", Tactic: "Reconnaissance", Description: "Brute force URLs, directories and DNS names"},
	{ID: "T1592", Name: "Gather Victim Host Information", Tactic: "Reconnaissance", Description: "Gather information about victim hosts"},
	{ID: "T1592.001", Name: "Hardware", Tactic: "Reconnaissance", Description: "Gather victim hardware information"},
	{ID: "T1592.002", Name: "Software", Tactic: "Reconnaissance", Description: "Gather victim software information"},
	{ID: "T1592.003", Name: "Firmware", Tactic: "Reconnaissance", Description: "Gather victim firmware information"},
	{ID: "T1592.004", Name: "Client Configurations", Tactic: "Reconnaissance", Description: "Gather victim client configuration info"},
	{ID: "T1589", Name: "Gather Victim Identity Information", Tactic: "Reconnaissance", Description: "Gather victim identity information"},
	{ID: "T1589.001", Name: "Credentials", Tactic: "Reconnaissance", Description: "Gather victim credentials"},
	{ID: "T1589.002", Name: "Email Addresses", Tactic: "Reconnaissance", Description: "Gather victim email addresses"},
	{ID: "T1589.003", Name: "Employee Names", Tactic: "Reconnaissance", Description: "Gather victim employee names"},
	{ID: "T1590", Name: "Gather Victim Network Information", Tactic: "Reconnaissance", Description: "Gather victim network information"},
	{ID: "T1590.001", Name: "Domain Properties", Tactic: "Reconnaissance", Description: "Gather victim domain properties"},
	{ID: "T1590.002", Name: "DNS", Tactic: "Reconnaissance", Description: "Gather victim DNS information"},
	{ID: "T1590.004", Name: "Network Topology", Tactic: "Reconnaissance", Description: "Gather victim network topology"},
	{ID: "T1590.005", Name: "IP Addresses", Tactic: "Reconnaissance", Description: "Gather victim IP addresses"},
	{ID: "T1590.006", Name: "Network Security Appliances", Tactic: "Reconnaissance", Description: "Gather info on network security appliances"},
	{ID: "T1591", Name: "Gather Victim Org Information", Tactic: "Reconnaissance", Description: "Gather victim organizational information"},
	{ID: "T1591.001", Name: "Determine Physical Locations", Tactic: "Reconnaissance", Description: "Determine physical locations of organization"},
	{ID: "T1591.002", Name: "Business Relationships", Tactic: "Reconnaissance", Description: "Gather business relationship information"},
	{ID: "T1591.004", Name: "Identify Roles", Tactic: "Reconnaissance", Description: "Identify key personnel roles"},
	{ID: "T1598", Name: "Phishing for Information", Tactic: "Reconnaissance", Description: "Send phishing messages to gather information"},
	{ID: "T1598.001", Name: "Spearphishing Service", Tactic: "Reconnaissance", Description: "Use third party services for spearphishing"},
	{ID: "T1598.002", Name: "Spearphishing Attachment", Tactic: "Reconnaissance", Description: "Send spearphishing attachments to gather info"},
	{ID: "T1598.003", Name: "Spearphishing Link", Tactic: "Reconnaissance", Description: "Send spearphishing links to gather information"},
	{ID: "T1597", Name: "Search Closed Sources", Tactic: "Reconnaissance", Description: "Search closed sources for victim information"},
	{ID: "T1596", Name: "Search Open Technical Databases", Tactic: "Reconnaissance", Description: "Search open technical databases"},
	{ID: "T1596.001", Name: "DNS/Passive DNS", Tactic: "Reconnaissance", Description: "Search DNS or passive DNS for information"},
	{ID: "T1596.002", Name: "WHOIS", Tactic: "Reconnaissance", Description: "Search WHOIS databases"},
	{ID: "T1596.003", Name: "Digital Certificates", Tactic: "Reconnaissance", Description: "Search digital certificate databases"},
	{ID: "T1596.004", Name: "CDNs", Tactic: "Reconnaissance", Description: "Search CDN data for information"},
	{ID: "T1596.005", Name: "Scan Databases", Tactic: "Reconnaissance", Description: "Search scan databases like Shodan and Censys"},
	{ID: "T1593", Name: "Search Open Websites/Domains", Tactic: "Reconnaissance", Description: "Search open websites and domains"},
	{ID: "T1593.001", Name: "Social Media", Tactic: "Reconnaissance", Description: "Search social media for information"},
	{ID: "T1593.002", Name: "Search Engines", Tactic: "Reconnaissance", Description: "Use search engines to gather information"},
	{ID: "T1593.003", Name: "Code Repositories", Tactic: "Reconnaissance", Description: "Search code repositories for information"},
	{ID: "T1594", Name: "Search Victim-Owned Websites", Tactic: "Reconnaissance", Description: "Search victim-owned websites for information"},

	// ── Resource Development ──
	{ID: "T1583", Name: "Acquire Infrastructure", Tactic: "Resource Development", Description: "Acquire infrastructure for operations"},
	{ID: "T1583.001", Name: "Domains", Tactic: "Resource Development", Description: "Acquire domains for operations"},
	{ID: "T1583.003", Name: "Virtual Private Server", Tactic: "Resource Development", Description: "Acquire VPS for operations"},
	{ID: "T1583.004", Name: "Server", Tactic: "Resource Development", Description: "Acquire servers for operations"},
	{ID: "T1583.006", Name: "Web Services", Tactic: "Resource Development", Description: "Use web services for operations"},
	{ID: "T1584", Name: "Compromise Infrastructure", Tactic: "Resource Development", Description: "Compromise third-party infrastructure"},
	{ID: "T1584.001", Name: "Domains", Tactic: "Resource Development", Description: "Compromise domains for operations"},
	{ID: "T1584.004", Name: "Server", Tactic: "Resource Development", Description: "Compromise servers for operations"},
	{ID: "T1587", Name: "Develop Capabilities", Tactic: "Resource Development", Description: "Develop custom capabilities"},
	{ID: "T1587.001", Name: "Malware", Tactic: "Resource Development", Description: "Develop custom malware"},
	{ID: "T1587.002", Name: "Code Signing Certificates", Tactic: "Resource Development", Description: "Develop code signing certificates"},
	{ID: "T1587.003", Name: "Digital Certificates", Tactic: "Resource Development", Description: "Develop digital certificates"},
	{ID: "T1587.004", Name: "Exploits", Tactic: "Resource Development", Description: "Develop exploits"},
	{ID: "T1588", Name: "Obtain Capabilities", Tactic: "Resource Development", Description: "Obtain capabilities for operations"},
	{ID: "T1588.001", Name: "Malware", Tactic: "Resource Development", Description: "Obtain malware for operations"},
	{ID: "T1588.002", Name: "Tool", Tactic: "Resource Development", Description: "Obtain tools for operations"},
	{ID: "T1588.005", Name: "Exploits", Tactic: "Resource Development", Description: "Obtain exploits for operations"},
	{ID: "T1588.006", Name: "Vulnerabilities", Tactic: "Resource Development", Description: "Obtain vulnerability information"},
	{ID: "T1585", Name: "Establish Accounts", Tactic: "Resource Development", Description: "Establish accounts for operations"},
	{ID: "T1586", Name: "Compromise Accounts", Tactic: "Resource Development", Description: "Compromise existing accounts"},
	{ID: "T1608", Name: "Stage Capabilities", Tactic: "Resource Development", Description: "Stage capabilities on infrastructure"},
	{ID: "T1608.001", Name: "Upload Malware", Tactic: "Resource Development", Description: "Upload malware to infrastructure"},
	{ID: "T1608.003", Name: "Install Digital Certificate", Tactic: "Resource Development", Description: "Install digital certificates"},
	{ID: "T1608.004", Name: "Drive-by Target", Tactic: "Resource Development", Description: "Stage drive-by compromise targets"},
	{ID: "T1608.005", Name: "Link Target", Tactic: "Resource Development", Description: "Stage links for targeting"},

	// ── Initial Access ──
	{ID: "T1189", Name: "Drive-by Compromise", Tactic: "Initial Access", Description: "Gain access through visiting a website"},
	{ID: "T1190", Name: "Exploit Public-Facing Application", Tactic: "Initial Access", Description: "Exploit vulnerabilities in internet-facing applications"},
	{ID: "T1133", Name: "External Remote Services", Tactic: "Initial Access", Description: "Leverage external-facing remote services"},
	{ID: "T1200", Name: "Hardware Additions", Tactic: "Initial Access", Description: "Introduce hardware devices to systems"},
	{ID: "T1566", Name: "Phishing", Tactic: "Initial Access", Description: "Send phishing messages to gain access"},
	{ID: "T1566.001", Name: "Spearphishing Attachment", Tactic: "Initial Access", Description: "Send spearphishing emails with attachments"},
	{ID: "T1566.002", Name: "Spearphishing Link", Tactic: "Initial Access", Description: "Send spearphishing emails with links"},
	{ID: "T1566.003", Name: "Spearphishing via Service", Tactic: "Initial Access", Description: "Send spearphishing via third-party services"},
	{ID: "T1091", Name: "Replication Through Removable Media", Tactic: "Initial Access", Description: "Move onto systems via removable media"},
	{ID: "T1195", Name: "Supply Chain Compromise", Tactic: "Initial Access", Description: "Manipulate products or delivery mechanisms"},
	{ID: "T1195.001", Name: "Compromise Software Dependencies", Tactic: "Initial Access", Description: "Manipulate software dependencies and packages"},
	{ID: "T1195.002", Name: "Compromise Software Supply Chain", Tactic: "Initial Access", Description: "Manipulate software supply chain"},
	{ID: "T1199", Name: "Trusted Relationship", Tactic: "Initial Access", Description: "Breach through trusted third party relationship"},
	{ID: "T1078", Name: "Valid Accounts", Tactic: "Initial Access", Description: "Use valid credentials to gain access"},
	{ID: "T1078.001", Name: "Default Accounts", Tactic: "Initial Access", Description: "Use default credentials"},
	{ID: "T1078.002", Name: "Domain Accounts", Tactic: "Initial Access", Description: "Use domain accounts"},
	{ID: "T1078.003", Name: "Local Accounts", Tactic: "Initial Access", Description: "Use local accounts"},
	{ID: "T1078.004", Name: "Cloud Accounts", Tactic: "Initial Access", Description: "Use cloud accounts"},

	// ── Execution ──
	{ID: "T1059", Name: "Command and Scripting Interpreter", Tactic: "Execution", Description: "Abuse command and script interpreters"},
	{ID: "T1059.001", Name: "PowerShell", Tactic: "Execution", Description: "Execute commands via PowerShell"},
	{ID: "T1059.003", Name: "Windows Command Shell", Tactic: "Execution", Description: "Execute commands via cmd.exe"},
	{ID: "T1059.004", Name: "Unix Shell", Tactic: "Execution", Description: "Execute commands via Unix shell"},
	{ID: "T1059.006", Name: "Python", Tactic: "Execution", Description: "Execute commands via Python"},
	{ID: "T1059.007", Name: "JavaScript", Tactic: "Execution", Description: "Execute commands via JavaScript"},
	{ID: "T1203", Name: "Exploitation for Client Execution", Tactic: "Execution", Description: "Exploit client application vulnerabilities"},
	{ID: "T1559", Name: "Inter-Process Communication", Tactic: "Execution", Description: "Abuse inter-process communication mechanisms"},
	{ID: "T1106", Name: "Native API", Tactic: "Execution", Description: "Interact with the native OS API"},
	{ID: "T1053", Name: "Scheduled Task/Job", Tactic: "Execution", Description: "Abuse task scheduling functionality"},
	{ID: "T1129", Name: "Shared Modules", Tactic: "Execution", Description: "Execute code via loading shared modules"},
	{ID: "T1072", Name: "Software Deployment Tools", Tactic: "Execution", Description: "Use software deployment tools for execution"},
	{ID: "T1569", Name: "System Services", Tactic: "Execution", Description: "Abuse system services for execution"},
	{ID: "T1204", Name: "User Execution", Tactic: "Execution", Description: "Rely on user interaction to execute"},
	{ID: "T1204.001", Name: "Malicious Link", Tactic: "Execution", Description: "User clicks a malicious link"},
	{ID: "T1204.002", Name: "Malicious File", Tactic: "Execution", Description: "User executes a malicious file"},
	{ID: "T1047", Name: "Windows Management Instrumentation", Tactic: "Execution", Description: "Abuse WMI for execution"},
	{ID: "T1611", Name: "Escape to Host", Tactic: "Execution", Description: "Break out of a container to the host"},

	// ── Persistence ──
	{ID: "T1098", Name: "Account Manipulation", Tactic: "Persistence", Description: "Manipulate accounts to maintain access"},
	{ID: "T1197", Name: "BITS Jobs", Tactic: "Persistence", Description: "Abuse BITS for persistence"},
	{ID: "T1547", Name: "Boot or Logon Autostart Execution", Tactic: "Persistence", Description: "Configure system to run program at boot/logon"},
	{ID: "T1547.001", Name: "Registry Run Keys / Startup Folder", Tactic: "Persistence", Description: "Use registry run keys or startup folder"},
	{ID: "T1136", Name: "Create Account", Tactic: "Persistence", Description: "Create new accounts for persistence"},
	{ID: "T1136.001", Name: "Local Account", Tactic: "Persistence", Description: "Create a local account"},
	{ID: "T1136.003", Name: "Cloud Account", Tactic: "Persistence", Description: "Create a cloud account"},
	{ID: "T1543", Name: "Create or Modify System Process", Tactic: "Persistence", Description: "Create or modify system processes"},
	{ID: "T1546", Name: "Event Triggered Execution", Tactic: "Persistence", Description: "Establish persistence via event triggers"},
	{ID: "T1133", Name: "External Remote Services", Tactic: "Persistence", Description: "Leverage external remote services"},
	{ID: "T1574", Name: "Hijack Execution Flow", Tactic: "Persistence", Description: "Hijack the execution flow of programs"},
	{ID: "T1525", Name: "Implant Internal Image", Tactic: "Persistence", Description: "Implant cloud or container images with backdoors"},
	{ID: "T1556", Name: "Modify Authentication Process", Tactic: "Persistence", Description: "Modify authentication mechanisms"},
	{ID: "T1137", Name: "Office Application Startup", Tactic: "Persistence", Description: "Leverage Office application startup features"},
	{ID: "T1542", Name: "Pre-OS Boot", Tactic: "Persistence", Description: "Abuse pre-OS boot mechanisms"},
	{ID: "T1505", Name: "Server Software Component", Tactic: "Persistence", Description: "Abuse server software components"},
	{ID: "T1505.003", Name: "Web Shell", Tactic: "Persistence", Description: "Install a web shell on a web server"},

	// ── Privilege Escalation ──
	{ID: "T1548", Name: "Abuse Elevation Control Mechanism", Tactic: "Privilege Escalation", Description: "Circumvent elevation control mechanisms"},
	{ID: "T1134", Name: "Access Token Manipulation", Tactic: "Privilege Escalation", Description: "Manipulate access tokens"},
	{ID: "T1068", Name: "Exploitation for Privilege Escalation", Tactic: "Privilege Escalation", Description: "Exploit vulnerabilities for privilege escalation"},
	{ID: "T1055", Name: "Process Injection", Tactic: "Privilege Escalation", Description: "Inject code into processes"},
	{ID: "T1053", Name: "Scheduled Task/Job", Tactic: "Privilege Escalation", Description: "Abuse task scheduling for privilege escalation"},

	// ── Defense Evasion ──
	{ID: "T1140", Name: "Deobfuscate/Decode Files or Information", Tactic: "Defense Evasion", Description: "Deobfuscate or decode files"},
	{ID: "T1070", Name: "Indicator Removal", Tactic: "Defense Evasion", Description: "Delete or modify indicators of compromise"},
	{ID: "T1070.001", Name: "Clear Windows Event Logs", Tactic: "Defense Evasion", Description: "Clear Windows event logs"},
	{ID: "T1070.003", Name: "Clear Command History", Tactic: "Defense Evasion", Description: "Clear command history"},
	{ID: "T1070.004", Name: "File Deletion", Tactic: "Defense Evasion", Description: "Delete files to remove indicators"},
	{ID: "T1562", Name: "Impair Defenses", Tactic: "Defense Evasion", Description: "Impair defensive capabilities"},
	{ID: "T1562.001", Name: "Disable or Modify Tools", Tactic: "Defense Evasion", Description: "Disable or modify security tools"},
	{ID: "T1562.002", Name: "Disable Windows Event Logging", Tactic: "Defense Evasion", Description: "Disable event logging"},
	{ID: "T1562.004", Name: "Disable or Modify System Firewall", Tactic: "Defense Evasion", Description: "Disable or modify firewalls"},
	{ID: "T1036", Name: "Masquerading", Tactic: "Defense Evasion", Description: "Manipulate features to appear legitimate"},
	{ID: "T1027", Name: "Obfuscated Files or Information", Tactic: "Defense Evasion", Description: "Encrypt, encode, or obfuscate content"},
	{ID: "T1207", Name: "Rogue Domain Controller", Tactic: "Defense Evasion", Description: "Register a rogue domain controller"},
	{ID: "T1014", Name: "Rootkit", Tactic: "Defense Evasion", Description: "Use rootkits to hide malicious activity"},
	{ID: "T1218", Name: "System Binary Proxy Execution", Tactic: "Defense Evasion", Description: "Proxy execution through trusted binaries"},
	{ID: "T1221", Name: "Template Injection", Tactic: "Defense Evasion", Description: "Inject templates for defense evasion"},
	{ID: "T1497", Name: "Virtualization/Sandbox Evasion", Tactic: "Defense Evasion", Description: "Detect and evade virtualization and sandboxes"},

	// ── Credential Access ──
	{ID: "T1110", Name: "Brute Force", Tactic: "Credential Access", Description: "Use brute force techniques to guess credentials"},
	{ID: "T1110.001", Name: "Password Guessing", Tactic: "Credential Access", Description: "Guess passwords to gain access"},
	{ID: "T1110.002", Name: "Password Cracking", Tactic: "Credential Access", Description: "Crack password hashes"},
	{ID: "T1110.003", Name: "Password Spraying", Tactic: "Credential Access", Description: "Use password spraying attacks"},
	{ID: "T1110.004", Name: "Credential Stuffing", Tactic: "Credential Access", Description: "Use leaked credential pairs"},
	{ID: "T1555", Name: "Credentials from Password Stores", Tactic: "Credential Access", Description: "Search password stores for credentials"},
	{ID: "T1212", Name: "Exploitation for Credential Access", Tactic: "Credential Access", Description: "Exploit vulnerabilities for credential access"},
	{ID: "T1187", Name: "Forced Authentication", Tactic: "Credential Access", Description: "Force authentication to capture credentials"},
	{ID: "T1056", Name: "Input Capture", Tactic: "Credential Access", Description: "Capture user input for credentials"},
	{ID: "T1056.001", Name: "Keylogging", Tactic: "Credential Access", Description: "Log keystrokes to capture credentials"},
	{ID: "T1557", Name: "Adversary-in-the-Middle", Tactic: "Credential Access", Description: "Position between endpoints to intercept traffic"},
	{ID: "T1111", Name: "Multi-Factor Authentication Interception", Tactic: "Credential Access", Description: "Intercept MFA mechanisms"},
	{ID: "T1003", Name: "OS Credential Dumping", Tactic: "Credential Access", Description: "Dump credentials from the operating system"},
	{ID: "T1528", Name: "Steal Application Access Token", Tactic: "Credential Access", Description: "Steal application access tokens"},
	{ID: "T1539", Name: "Steal Web Session Cookie", Tactic: "Credential Access", Description: "Steal web session cookies"},
	{ID: "T1552", Name: "Unsecured Credentials", Tactic: "Credential Access", Description: "Search for unsecured credential storage"},
	{ID: "T1552.001", Name: "Credentials In Files", Tactic: "Credential Access", Description: "Search files for credentials"},
	{ID: "T1552.005", Name: "Cloud Instance Metadata API", Tactic: "Credential Access", Description: "Access cloud instance metadata API"},

	// ── Discovery ──
	{ID: "T1087", Name: "Account Discovery", Tactic: "Discovery", Description: "Enumerate accounts on a system"},
	{ID: "T1010", Name: "Application Window Discovery", Tactic: "Discovery", Description: "Discover open application windows"},
	{ID: "T1217", Name: "Browser Information Discovery", Tactic: "Discovery", Description: "Enumerate browser information"},
	{ID: "T1580", Name: "Cloud Infrastructure Discovery", Tactic: "Discovery", Description: "Discover cloud infrastructure resources"},
	{ID: "T1613", Name: "Container and Resource Discovery", Tactic: "Discovery", Description: "Discover containers and container resources"},
	{ID: "T1083", Name: "File and Directory Discovery", Tactic: "Discovery", Description: "Enumerate files and directories"},
	{ID: "T1046", Name: "Network Service Discovery", Tactic: "Discovery", Description: "Discover services running on remote hosts"},
	{ID: "T1135", Name: "Network Share Discovery", Tactic: "Discovery", Description: "Discover shared network resources"},
	{ID: "T1040", Name: "Network Sniffing", Tactic: "Discovery", Description: "Sniff network traffic for information"},
	{ID: "T1201", Name: "Password Policy Discovery", Tactic: "Discovery", Description: "Discover password policy information"},
	{ID: "T1120", Name: "Peripheral Device Discovery", Tactic: "Discovery", Description: "Discover peripheral devices"},
	{ID: "T1057", Name: "Process Discovery", Tactic: "Discovery", Description: "Discover running processes"},
	{ID: "T1018", Name: "Remote System Discovery", Tactic: "Discovery", Description: "Discover remote systems on a network"},
	{ID: "T1518", Name: "Software Discovery", Tactic: "Discovery", Description: "Discover installed software"},
	{ID: "T1082", Name: "System Information Discovery", Tactic: "Discovery", Description: "Discover system information"},
	{ID: "T1016", Name: "System Network Configuration Discovery", Tactic: "Discovery", Description: "Discover network configuration"},
	{ID: "T1049", Name: "System Network Connections Discovery", Tactic: "Discovery", Description: "Discover network connections"},
	{ID: "T1033", Name: "System Owner/User Discovery", Tactic: "Discovery", Description: "Discover system owner/user"},
	{ID: "T1007", Name: "System Service Discovery", Tactic: "Discovery", Description: "Discover system services"},

	// ── Lateral Movement ──
	{ID: "T1210", Name: "Exploitation of Remote Services", Tactic: "Lateral Movement", Description: "Exploit remote services to move laterally"},
	{ID: "T1534", Name: "Internal Spearphishing", Tactic: "Lateral Movement", Description: "Use spearphishing within the organization"},
	{ID: "T1570", Name: "Lateral Tool Transfer", Tactic: "Lateral Movement", Description: "Transfer tools between systems"},
	{ID: "T1563", Name: "Remote Service Session Hijacking", Tactic: "Lateral Movement", Description: "Hijack remote service sessions"},
	{ID: "T1021", Name: "Remote Services", Tactic: "Lateral Movement", Description: "Use remote services for lateral movement"},
	{ID: "T1021.001", Name: "Remote Desktop Protocol", Tactic: "Lateral Movement", Description: "Use RDP for lateral movement"},
	{ID: "T1021.002", Name: "SMB/Windows Admin Shares", Tactic: "Lateral Movement", Description: "Use SMB/admin shares for lateral movement"},
	{ID: "T1021.004", Name: "SSH", Tactic: "Lateral Movement", Description: "Use SSH for lateral movement"},
	{ID: "T1080", Name: "Taint Shared Content", Tactic: "Lateral Movement", Description: "Add malicious content to shared resources"},
	{ID: "T1550", Name: "Use Alternate Authentication Material", Tactic: "Lateral Movement", Description: "Use non-standard authentication material"},

	// ── Collection ──
	{ID: "T1557", Name: "Adversary-in-the-Middle", Tactic: "Collection", Description: "Position to intercept and modify network traffic"},
	{ID: "T1560", Name: "Archive Collected Data", Tactic: "Collection", Description: "Archive data for exfiltration"},
	{ID: "T1185", Name: "Browser Session Hijacking", Tactic: "Collection", Description: "Exploit browser sessions to capture data"},
	{ID: "T1530", Name: "Data from Cloud Storage", Tactic: "Collection", Description: "Access data from cloud storage"},
	{ID: "T1213", Name: "Data from Information Repositories", Tactic: "Collection", Description: "Collect data from information repositories"},
	{ID: "T1005", Name: "Data from Local System", Tactic: "Collection", Description: "Collect data from the local system"},
	{ID: "T1039", Name: "Data from Network Shared Drive", Tactic: "Collection", Description: "Collect data from network shares"},
	{ID: "T1025", Name: "Data from Removable Media", Tactic: "Collection", Description: "Collect data from removable media"},
	{ID: "T1074", Name: "Data Staged", Tactic: "Collection", Description: "Stage collected data for exfiltration"},
	{ID: "T1114", Name: "Email Collection", Tactic: "Collection", Description: "Collect email data"},
	{ID: "T1113", Name: "Screen Capture", Tactic: "Collection", Description: "Capture screen contents"},
	{ID: "T1125", Name: "Video Capture", Tactic: "Collection", Description: "Record video output"},

	// ── Command and Control ──
	{ID: "T1071", Name: "Application Layer Protocol", Tactic: "Command and Control", Description: "Communicate using application layer protocols"},
	{ID: "T1071.001", Name: "Web Protocols", Tactic: "Command and Control", Description: "Communicate using HTTP/HTTPS"},
	{ID: "T1071.002", Name: "File Transfer Protocols", Tactic: "Command and Control", Description: "Communicate using FTP/SFTP"},
	{ID: "T1071.003", Name: "Mail Protocols", Tactic: "Command and Control", Description: "Communicate using SMTP/IMAP"},
	{ID: "T1071.004", Name: "DNS", Tactic: "Command and Control", Description: "Communicate using DNS"},
	{ID: "T1132", Name: "Data Encoding", Tactic: "Command and Control", Description: "Encode data for C2 communication"},
	{ID: "T1001", Name: "Data Obfuscation", Tactic: "Command and Control", Description: "Obfuscate C2 traffic"},
	{ID: "T1568", Name: "Dynamic Resolution", Tactic: "Command and Control", Description: "Dynamically resolve C2 addresses"},
	{ID: "T1573", Name: "Encrypted Channel", Tactic: "Command and Control", Description: "Encrypt C2 communications"},
	{ID: "T1008", Name: "Fallback Channels", Tactic: "Command and Control", Description: "Use fallback C2 channels"},
	{ID: "T1105", Name: "Ingress Tool Transfer", Tactic: "Command and Control", Description: "Transfer tools into the environment"},
	{ID: "T1104", Name: "Multi-Stage Channels", Tactic: "Command and Control", Description: "Use multi-stage C2 channels"},
	{ID: "T1095", Name: "Non-Application Layer Protocol", Tactic: "Command and Control", Description: "Communicate using non-application layer protocols"},
	{ID: "T1571", Name: "Non-Standard Port", Tactic: "Command and Control", Description: "Communicate using non-standard ports"},
	{ID: "T1572", Name: "Protocol Tunneling", Tactic: "Command and Control", Description: "Tunnel traffic through other protocols"},
	{ID: "T1090", Name: "Proxy", Tactic: "Command and Control", Description: "Use proxies for C2 communication"},
	{ID: "T1219", Name: "Remote Access Software", Tactic: "Command and Control", Description: "Use legitimate remote access tools"},
	{ID: "T1102", Name: "Web Service", Tactic: "Command and Control", Description: "Use web services for C2"},

	// ── Exfiltration ──
	{ID: "T1020", Name: "Automated Exfiltration", Tactic: "Exfiltration", Description: "Automatically exfiltrate data"},
	{ID: "T1030", Name: "Data Transfer Size Limits", Tactic: "Exfiltration", Description: "Limit data transfer sizes to avoid detection"},
	{ID: "T1048", Name: "Exfiltration Over Alternative Protocol", Tactic: "Exfiltration", Description: "Exfiltrate data over alternative protocol"},
	{ID: "T1041", Name: "Exfiltration Over C2 Channel", Tactic: "Exfiltration", Description: "Exfiltrate data over the C2 channel"},
	{ID: "T1011", Name: "Exfiltration Over Other Network Medium", Tactic: "Exfiltration", Description: "Exfiltrate data over alternative network"},
	{ID: "T1052", Name: "Exfiltration Over Physical Medium", Tactic: "Exfiltration", Description: "Exfiltrate data over physical medium"},
	{ID: "T1567", Name: "Exfiltration Over Web Service", Tactic: "Exfiltration", Description: "Exfiltrate data over web services"},
	{ID: "T1029", Name: "Scheduled Transfer", Tactic: "Exfiltration", Description: "Schedule data exfiltration"},

	// ── Impact ──
	{ID: "T1531", Name: "Account Access Removal", Tactic: "Impact", Description: "Interrupt account access"},
	{ID: "T1485", Name: "Data Destruction", Tactic: "Impact", Description: "Destroy data on target systems"},
	{ID: "T1486", Name: "Data Encrypted for Impact", Tactic: "Impact", Description: "Encrypt data for ransomware"},
	{ID: "T1565", Name: "Data Manipulation", Tactic: "Impact", Description: "Manipulate data to affect business processes"},
	{ID: "T1491", Name: "Defacement", Tactic: "Impact", Description: "Deface internal or external systems"},
	{ID: "T1491.001", Name: "Internal Defacement", Tactic: "Impact", Description: "Deface internal systems"},
	{ID: "T1491.002", Name: "External Defacement", Tactic: "Impact", Description: "Deface external systems"},
	{ID: "T1561", Name: "Disk Wipe", Tactic: "Impact", Description: "Wipe disk data"},
	{ID: "T1499", Name: "Endpoint Denial of Service", Tactic: "Impact", Description: "Perform endpoint DoS"},
	{ID: "T1498", Name: "Network Denial of Service", Tactic: "Impact", Description: "Perform network DoS"},
	{ID: "T1496", Name: "Resource Hijacking", Tactic: "Impact", Description: "Hijack resources for cryptomining etc"},
	{ID: "T1489", Name: "Service Stop", Tactic: "Impact", Description: "Stop or disable services"},
	{ID: "T1529", Name: "System Shutdown/Reboot", Tactic: "Impact", Description: "Shutdown or reboot systems"},
}

// GetMitreFullMatrix returns the full matrix endpoint data organized by tactic.
func GetMitreFullMatrix() map[string][]MitreTechnique {
	result := make(map[string][]MitreTechnique)
	for _, tech := range FullMitreMatrix {
		result[tech.Tactic] = append(result[tech.Tactic], tech)
	}
	return result
}
